"""Quarterly rolling recalibration over the 2023-2024 test period.

Electricity-price forecasting benchmarks refit their models as new data
arrive (Lago et al., 2021, recalibrate daily). Here each model is refit before
every test quarter: refit ``k`` trains on all data from 2015 up to three months
before the quarter, selects its checkpoint on those three months, and
forecasts the origins of the quarter. Stitched together, the eight quarters
cover exactly the origins of the static test split, so the results are
directly comparable with it.

``make-configs`` writes one configuration per quarter (``data.relabel_splits``
relabels rows by period; rows outside every period are used only as history).
``collect`` predicts each quarter with its refit and writes, per region, the
seed-stacked test predictions (as ``protocol_alignment collect``) and
RE-Price style metrics per seed (as ``evaluate_paper_metrics``).
``stitch-baselines`` joins the per-quarter outputs of ``forecasting.baselines``
(run on the quarter configurations) into one test forecast per seed.
"""

from __future__ import annotations

import argparse
import copy
import json
import os
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import yaml

from .datasets import build_region_datasets, load_forecast_config
from .evaluate_paper_metrics import collect_predictions, point_metrics, probabilistic_metrics
from .train import build_model, resolve_device

REGIONS = ("NSW1", "QLD1", "TAS1")
SEEDS = (2026, 2027, 2028)
QUARTERS = pd.date_range("2023-01-01", "2025-01-01", freq="QS")  # 9 edges, 8 quarters
TRAIN_START = "2015-01-01 00:00:00"
TEST_END = pd.Timestamp("2025-01-01")
VALIDATION_MONTHS = 3
if os.environ.get("ROLLING_PERIOD") == "holdout":
    # Held-out period 2025-01 to 2025-07: AEMO stopped the OUTAGE_LRC PD PASA run type after July 2025, so the
    # pipeline of the main period is only intact up to then (see logs/forecasting/holdout_data/README.md).
    QUARTERS = pd.DatetimeIndex(["2025-01-01", "2025-04-01", "2025-07-01", "2025-07-30"])
    TEST_END = pd.Timestamp("2025-07-31")


def _stamp(value: pd.Timestamp) -> str:
    return value.strftime("%Y-%m-%d %H:%M:%S")


def quarter_config_path(name: str, quarter: int) -> Path:
    return Path("configs") / f"aemo_forecast_rolling_{name}_q{quarter}.yaml"


def make_configs(base_config: Path, name: str) -> list[Path]:
    base = yaml.safe_load(base_config.read_text())
    paths = []
    for k in range(len(QUARTERS) - 1):
        start, end = QUARTERS[k], QUARTERS[k + 1]
        validation_start = start - pd.DateOffset(months=VALIDATION_MONTHS)
        # The quarter's last origins forecast up to 23 hours into the next
        # quarter; those hours are targets of this refit, not of the next one.
        test_end = min(end + pd.Timedelta(hours=23), TEST_END)
        config = copy.deepcopy(base)
        config["data"]["relabel_splits"] = True
        config["data"]["split_boundaries"] = {
            "train": {"start": TRAIN_START, "end_exclusive": _stamp(validation_start)},
            "validation": {"start": _stamp(validation_start), "end_exclusive": _stamp(start)},
            "test": {"start": _stamp(start), "end_exclusive": _stamp(test_end)},
        }
        config["training"]["output_directory"] = f"outputs/forecasting/rolling/{name}/q{k}"
        path = quarter_config_path(name, k)
        header = (f"# Generated by forecasting.rolling from {base_config.name}: refit {k} for the test "
                  f"quarter starting {start.date()}.\n")
        path.write_text(header + yaml.safe_dump(config, sort_keys=False))
        paths.append(path)
    return paths


def _checkpoint(config: dict, seed: int, region: str) -> Path:
    directory = config["training"]["output_directory"]
    if seed != SEEDS[0]:
        directory += f"_seed{seed}"
    return Path(config["project_root"]) / directory / region / "best_model.pt"


def collect(name: str, static_npz_dir: Path, output_dir: Path, metrics_dir: Path, device_name: str) -> None:
    device = resolve_device(device_name)
    output_dir.mkdir(parents=True, exist_ok=True)
    for region in REGIONS:
        with np.load(static_npz_dir / f"{region}.npz") as archive:
            static_origins = archive["origin_unix"]
        per_seed = {seed: {"point": [], "quantile": [], "actual": [], "naive": [], "origin": []} for seed in SEEDS}
        levels = None
        for k in range(len(QUARTERS) - 1):
            config_path = quarter_config_path(name, k)
            config = load_forecast_config(config_path)
            dataset = build_region_datasets(config_path, region)["test"]
            origins = dataset.delivery_unix_seconds[np.asarray(dataset.origin_indices)]
            for seed in SEEDS:
                model = build_model(config).to(device)
                checkpoint = torch.load(_checkpoint(config, seed, region), map_location=device, weights_only=False)
                model.load_state_dict(checkpoint["model_state"])
                model.set_epoch(checkpoint.get("model_epoch", checkpoint["best_epoch"]))
                levels = [float(level) for level in model.quantiles]
                predictions = collect_predictions(model, dataset, device, 1024)
                for key in ("point", "quantile", "actual", "naive"):
                    per_seed[seed][key].append(predictions[key])
                per_seed[seed]["origin"].append(origins)
        stacked = {seed: {key: np.concatenate(values) for key, values in parts.items()} for seed, parts in per_seed.items()}
        origins = stacked[SEEDS[0]]["origin"]
        if not np.array_equal(origins, static_origins):
            raise ValueError(f"{region}: stitched origins do not match the static test split")
        actual = stacked[SEEDS[0]]["actual"]
        np.savez_compressed(
            output_dir / f"{region}.npz",
            point=np.stack([stacked[s]["point"] for s in SEEDS]),
            quantile=np.stack([stacked[s]["quantile"] for s in SEEDS]),
            actual=actual,
            naive=stacked[SEEDS[0]]["naive"],
            origin_unix=origins,
        )
        for seed in SEEDS:
            metrics = point_metrics(stacked[seed]["point"], actual) | probabilistic_metrics(
                stacked[seed]["quantile"], actual, levels
            )
            path = metrics_dir / f"seed{seed}" / f"{region}.json"
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps({"region": region, "rolling": name, "test": {"model": metrics}}, indent=2))
        print(f"collected {name} {region}: {len(origins)} origins, "
              f"MAE {np.mean([point_metrics(stacked[s]['point'], actual)['mae'] for s in SEEDS]):.2f}", flush=True)


def stitch_baselines(root: Path, static_npz_dir: Path, metrics_dir: Path) -> None:
    """Joins ``root/seed<S>/q<k>/<region>.npz`` into ``root/seed<S>/<region>.npz``."""
    levels = [0.05, 0.10, 0.50, 0.90, 0.95]
    for seed in SEEDS:
        for region in REGIONS:
            with np.load(static_npz_dir / f"{region}.npz") as archive:
                static_origins = archive["origin_unix"]
            parts = {"point": [], "quantile": [], "actual": [], "origin_unix": []}
            for k in range(len(QUARTERS) - 1):
                with np.load(root / f"seed{seed}" / f"q{k}" / f"{region}.npz") as archive:
                    for key in parts:
                        parts[key].append(archive[key])
            stitched = {key: np.concatenate(values) for key, values in parts.items()}
            if not np.array_equal(stitched["origin_unix"], static_origins):
                raise ValueError(f"{root} seed {seed} {region}: stitched origins do not match the static test split")
            np.savez_compressed(root / f"seed{seed}" / f"{region}.npz", **stitched)
            metrics = point_metrics(stitched["point"], stitched["actual"]) | probabilistic_metrics(
                stitched["quantile"], stitched["actual"], levels
            )
            path = metrics_dir / f"seed{seed}" / f"{region}.json"
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps({"region": region, "rolling": str(root), "seed": seed, "test": metrics}, indent=2))
        print(f"stitched {root} seed {seed}", flush=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    commands = parser.add_subparsers(dest="command", required=True)
    make_parser = commands.add_parser("make-configs")
    make_parser.add_argument("--base-config", required=True, type=Path)
    make_parser.add_argument("--name", required=True)
    collect_parser = commands.add_parser("collect")
    collect_parser.add_argument("--name", required=True)
    collect_parser.add_argument("--static-npz-dir", required=True, type=Path,
                                help="seed-stacked static test predictions, for the origin check")
    collect_parser.add_argument("--output-dir", required=True, type=Path)
    collect_parser.add_argument("--metrics-dir", required=True, type=Path)
    collect_parser.add_argument("--device", default="cuda")
    stitch_parser = commands.add_parser("stitch-baselines")
    stitch_parser.add_argument("--root", required=True, type=Path, help="contains seed<S>/q<k>/<region>.npz")
    stitch_parser.add_argument("--static-npz-dir", required=True, type=Path)
    stitch_parser.add_argument("--metrics-dir", required=True, type=Path)
    args = parser.parse_args()
    if args.command == "make-configs":
        for path in make_configs(args.base_config, args.name):
            print(path)
    elif args.command == "collect":
        collect(args.name, args.static_npz_dir, args.output_dir, args.metrics_dir, args.device)
    else:
        stitch_baselines(args.root, args.static_npz_dir, args.metrics_dir)


if __name__ == "__main__":
    main()
